### PR TITLE
Increase cloning depth for a companion merge

### PR DESCRIPTION
**Pull request by rcny**

### CODE REVIEW

**Comment by rcny** [comment]
Fixes [this](https://gitlab.parity.io/parity/substrate/-/jobs/1269169).

**Comment by rcny** [comment]
> Fixes [this](https://gitlab.parity.io/parity/substrate/-/jobs/1269169).

Got confirmation from @bkchr.

**Comment by joao-paulo-parity** [comment]
@rcny what was the thought process or reasoning for this change?

Only the HEAD code is used for the integration, so cloning more of the history should not matter for anything.

**Comment by bkchr** [comment]
@joao-paulo-parity we now merge master into the companion and the local branch. That required this.

**Comment by bkchr** [comment]
Let's assume you have a pr that doesn't require any companion. It builds fine with Polkadot, however in the mean time someone merged a breaking change. You will try to compile with Polkadot master, but that will fail because you don't have the required Substrate changes in your branch. Merging master into the Polkadot companion makes it easier for you when you have merged master into your Substrate branch, because you don't need to update the Polkadot companion.

**Pull request merged**
