### PR TITLE
bench-bot: display hardware specs at the start of the command

### LINKED ISSUE #55: bench-bot: display machine specs at the start of command
From https://github.com/paritytech/bench-bot/issues/8

### PR DESCRIPTION
**Pull request by joao-paulo-parity**
close #55

### CODE REVIEW

**Comment by Gioyik** [comment]
@joao-paulo-parity could you please explain me why the `2>/dev/null` is before the command of how do you want that to behave? I don't think `set -x` out error level logs to be catch by that but maybe I'm missing something.

**Comment by joao-paulo-parity** [comment]
@Gioyik the 2>/dev/null avoids some noisy error message due to the command not being run as root. You can test it locally as well

```console
$ >/dev/null lshw -short -sanitize
WARNING: you should run this program as super-user.
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.
```

**Comment by Gioyik** [comment]
ah, so that sections is intended for the `lsw...`, got confused because I usually see it at the right side, instead of the left side.

The more you know :)

**Review by Gioyik — APPROVED** [review]

**Comment by joao-paulo-parity** [comment]
> I usually see it at the right side, instead of the left side

Me too! I only learned about doing it this way a few months ago.

Thanks for the review.

**Pull request merged**
