### PR TITLE
Check workspace script

### PR DESCRIPTION
**Pull request by ggwpez**
A script to check workspace integrity. Otherwise it constantly gets messed up and i fixed it manually four times now.

### CODE REVIEW

**Comment by mordamax** [comment]
@ggwpez curious why in pipeline-scripts? 
is it used in more than 1 repo (polkadot-sdk)? 
I was hoping we could deprecate this repo at all, and move everything to polkadot-sdk, unless there's a need to re-use it in more repos

**Comment by ggwpez** [comment]
> @ggwpez curious why in pipeline-scripts? is it used in more than 1 repo (polkadot-sdk)? I was hoping we could deprecate this repo at all, and move something that is still in use to polkadot-sdk, unless there's a need to re-use it in more repos

Well, i twould be nice to also use it in the runtimes repo. But we dont have to fork it here, it can stay in the other repo i guess.

**Comment by mordamax** [comment]
there's also https://github.com/paritytech/scripts
cc @paritytech/ci may be you could recommend something
i'd archive this repo imo

**Comment by rcny** [comment]
I think we should add it to `polkadot-sdk` and use it as needed in other projects. Regarding https://github.com/paritytech/scripts, it currently serves mainly for hosting Dockerfiles, as [explicitly stated](https://github.com/paritytech/scripts#but-what-about-scripts), but we can reevaluate it if someone has a strong opposition to incorporating the script into `polkadot-sdk`.

**Comment by mordamax** [comment]
@alvicsam there's also that https://github.com/paritytech/individuality/blob/e1006e39dbed432750d48b1fb57bf5cba6a13d54/.gitlab/pipeline/check.yml#L71

**Pull request closed without merging**
